name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
version: VERSION
core: 8.x
hidden: true

# Information added by drush on 2019-02-06
version: '8.6.8'
project: 'drupal'
datestamp: 1549466032