name: 'Settings Tray'
type: module
description: 'Provides a sidebar to configure blocks on the page.'
package: Core
version: VERSION
core: 8.x
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual

# Information added by drush on 2019-02-06
version: '8.6.8'
project: 'drupal'
datestamp: 1549466032